### ISSUE TITLE
Is it convenient for you to open complete data sets?

### ISSUE THREAD

**Issue by bzGeng** [ZixuanKe/LifelongSentClass#1]
Is it convenient for you to open the complete data set mentioned in the paper? I hope to continue the study in this direction, I would be very grateful if the dataset is available.

**Comment by ZixuanKe** [comment]
Thank you for your interest. 
Yes, please check "https://github.com/ZixuanKe/LifelongSentClass/tree/master/dat/dsc"
Note that you may have to process the data yourself.

**Comment by bzGeng** [comment]
Thanks a lot, looking forward to your future works!
