### ISSUE TITLE
Why RNN?

### ISSUE THREAD

**Issue by itsmemala** [ZixuanKe/LifelongSentClass#2]
Hello, I'm wondering why you've chosen RNN as the main CL network? Did you try other networks such as MLP or CNN - what was the performance difference you observed?

**Comment by ZixuanKe** [comment]
Thank you so much for your interest. When we worked on this project, RNN was still the standard practice in NLP. We didn’t try MLP or CNN. Indeed, one can use any other backbone model, see [PyConitnual](https://github.com/ZixuanKe/PyContinual) for the Transformer one (KAN is included in the framework).
